CREATE DATABASE DvdLibrary

USE DvdLibrary
GO

CREATE TABLE Dvds (
	DvdId INT PRIMARY KEY IDENTITY NOT NULL,
	Title NVARCHAR(40) NOT NULL,
	RealeaseYear VARCHAR(4) NOT NULL,
	Director NVARCHAR(60) NOT NULL,
	Rating NVARCHAR(5) NOT NULL,
	Notes NVARCHAR(100) NULL,
);