USE GuildCars
GO

CREATE TABLE Specials (
SpecialId INT PRIMARY KEY IDENTITY NOT NULL,
SpecialTitle NVARCHAR(30) NOT NULL,
SpecialDescription NVARCHAR(500) NOT NULL
);

USE GuildCars
GO

CREATE TABLE Makes (
MakeId INT PRIMARY KEY IDENTITY NOT NULL,
MakeName NVARCHAR(20) NOT NULL,
DateCreated NVARCHAR(10) NOT NULL,
UserId NVARCHAR(128) FOREIGN KEY REFERENCES AspNetUsers (Id) NOT NULL
);

USE GuildCars
GO

CREATE TABLE Models (
ModelId INT PRIMARY KEY IDENTITY NOT NULL,
ModelName NVARCHAR(55) NOT NULL,
ModelYear NVARCHAR(4) NOT NULL,
DateCreated NVARCHAR(10) NOT NULL,
MakeId INT FOREIGN KEY REFERENCES Makes (MakeId) NOT NULL,
UserId NVARCHAR(128) FOREIGN KEY REFERENCES AspNetUsers (Id) NOT NULL
);

USE GuildCars
GO

CREATE TABLE Colors (
ColorId INT PRIMARY KEY IDENTITY NOT NULL,
ColorName NVARCHAR(25) NOT NULL
);

USE GuildCars
GO

CREATE TABLE BodyStyles (
BodyStyleId INT PRIMARY KEY IDENTITY NOT NULL,
BodyStyleName NVARCHAR(15) NOT NULL
);

USE GuildCars
GO

CREATE TABLE Interiors (
InteriorId INT PRIMARY KEY IDENTITY NOT NULL,
InteriorName NVARCHAR(75) NOT NULL
);

USE GuildCars
GO

CREATE TABLE Vehicles (
VehicleId INT PRIMARY KEY IDENTITY NOT NULL,
Type NVARCHAR(4) NOT NULL,
Transmission NVARCHAR(15) NOT NULL,
Mileage INT NOT NULL,
VIN VARCHAR(17) NOT NULL,
MSRP DECIMAL NOT NULL,
Price DECIMAL NOT NULL,
Description NVARCHAR(250) NULL,
DateCreated NVARCHAR(10) NOT NULL,
Picture NVARCHAR(250) NOT NULL,
Featured BIT NOT NULL, 

ModelId INT FOREIGN KEY REFERENCES Models (ModelId) NOT NULL,
BodyStyleId INT FOREIGN KEY REFERENCES BodyStyles(BodyStyleId) NOT NULL,
ColorId INT FOREIGN KEY REFERENCES Colors (ColorId) NOT NULL,
InteriorId INT FOREIGN KEY REFERENCES Interiors (InteriorId) NOT NULL,
UserId NVARCHAR(128) FOREIGN KEY REFERENCES AspNetUsers (Id) NOT NULL
);

USE GuildCars
GO

/*State can/will be hardcoded*/
CREATE TABLE Purchases (
PurchaseId INT PRIMARY KEY IDENTITY NOT NULL,
VehicleId INT FOREIGN KEY REFERENCES Vehicles (VehicleId) NOT NULL,
PurchasePrice DECIMAL NOT NULL,
PurchaseType NVARCHAR(15) NOT NULL,
Name NVARCHAR(60) NOT NULL,
PhoneNumber NVARCHAR(15) NOT NULL,
Email NVARCHAR(40) NOT NULL,
Street1 NVARCHAR(30) NOT NULL,
Street2 NVARCHAR(30) NULL,
City NVARCHAR(50) NOT NULL,
ZipCode NVARCHAR (5) NOT NULL,
StateAbbreviation VARCHAR(2) NOT NULL,
DateCreated NVARCHAR(10) NOT NULL,
UserId NVARCHAR(128) NOT NULL
);

CREATE TABLE Contacts (
ContactId INT PRIMARY KEY IDENTITY NOT NULL,
Name NVARCHAR(60) NOT NULL,
Email NVARCHAR(40) NULL,
Message NVARCHAR(500) NOT NULL,
Phone NVARCHAR(15) NULL,
);